CREATE SCHEMA inter;

CREATE TABLE inter.USUARIO (
	ID_USUARIO INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	NOME VARCHAR(100),
	EMAIL VARCHAR(100),
	CONSTRAINT USUARIO_PK PRIMARY KEY (ID_USUARIO)
);

CREATE TABLE inter.RESULTADO (
	ID_RESULTADO INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	INTEIRO_N DOUBLE,
	MULTIPLICADOR_K DOUBLE,
	RESULT_DIGITO_UNICO DOUBLE,
	ID_USUARIO INTEGER,
	CONSTRAINT RESULTADO_PK PRIMARY KEY (ID_RESULTADO),
	CONSTRAINT RESULTADO_FK FOREIGN KEY (ID_USUARIO) REFERENCES inter.USUARIO(ID_USUARIO)
);
